# Generated by Django 4.2.1 on 2023-05-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_api', '0002_alter_planet_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
